spring:
  application:
    name: hotel-booking-system
  
  datasource:
    url: jdbc:h2:file:./data/hoteldb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:luxestay.booking@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    test-connection: false

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecureSecretKeyThatIsAtLeast256BitsLongForHMACAlgorithmSecurity12345}
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: false

# Gemini AI Configuration
gemini:
  api:
    key: gemini api key
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

logging:
  level:
    com.hotelbooking: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
    com.hotelbooking.service.GeminiEmailService: INFO
